### ISSUE TITLE
Verification also succeeds on 1st day of the month

### ISSUE THREAD

**Issue by 0xm3rlin** [Abracadabra-money/abracadabra-money-contracts#36]
https://github.com/Abracadabra-money/abracadabra-money-foundry/blob/1a4cc57f8aeef230b669429692710c3bb16f57a1/src/periphery/MSpellSender.sol#L122

This verification also succeeds if lastUpdated = 0

**Comment by 0xCalibur** [comment]
BokkyPooBahsDateTimeLibrary should not be used anymore in the next MSpell iteration and controlled by gelato with onlyOperator. If we decide to use the library again, I suggest we use forge lib pointing to the lib git repo instead
